# Generated by Django 3.0.5 on 2020-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='Local',
        ),
        migrations.AddField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
